spring:
  application:
    name: nexus-lite
  datasource:
    hikari:

      jdbc-url:               <DB CONNECTION STRING>
      username:               <DB USERNAME>
      password:               <DB PASSWORD>
      driver-class-name:      oracle.jdbc.OracleDriver
      maximum-pool-size:      20
      minimum-idle:           2
      connection-timeout:     19000
      idle-timeout:           450000
      max-lifetime:           800000
      data-source-properties:
        defaultRowPrefetch:        100
        implicitCachingEnabled:    true
        fastConnectionFailoverEnabled: true
        implicitStatementCacheSize:   50

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 7003

logging:
  level:
    root: info

# Add your custom properties here
app:
  datasource:
    schema-name:           # Schema name
    log-table-name: swtbs_txn_log   # Optional: Defaults to swtbs_txn_log if omitted
    hist-table-name: swtbs_txn_hist # Optional: Set to query history table, leave blank/omit otherwise
    rtl-table-name: detbs_rtl_teller # Optional: Defaults to detbs_rtl_teller if omitted


fcubs:
  wsdl-url: "http://X.X.X.X:XXXX" # Replace with the actual WSDL URL of your bank
  header:
    user-id: "XXXXX" #Replace with actual user ID
    branch: "XXX" #Replace with actual branch code
    source: "XXXX" #Replace with the actual source
    ubscomp: "FCUBS"