spring:
  application:
    name: nexus-lite
  profiles:
    active: h2
  # Database configuration moved to application-h2.yml and application-mysql.yml
  # Use profiles to switch between configurations

server:
  port: 7003

logging:
  level:
    root: info

# Add your custom properties here
app:
  datasource:
    schema-name:           # Schema name
    log-table-name: swtbs_txn_log   # Optional: Defaults to swtbs_txn_log if omitted
    hist-table-name: swtbs_txn_hist # Optional: Set to query history table, leave blank/omit otherwise
    rtl-table-name: detbs_rtl_teller # Optional: Defaults to detbs_rtl_teller if omitted


fcubs:
  wsdl-url: "http://X.X.X.X:XXXX" # Replace with the actual WSDL URL of your bank
  header:
    user-id: "XXXXX" #Replace with actual user ID
    branch: "XXX" #Replace with actual branch code
    source: "XXXX" #Replace with the actual source
    ubscomp: "FCUBS"