spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexusdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
